spring:
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop                # ddl 자동 작성 여부

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # DB 드라이버
    url: jdbc:mysql://localhost:3306/plancard?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true       # 데이터베이스 URL
    username: ssafy                     # 데이터베이스 계정명
    password: ssafy                       # 데이터베이스 계정 비밀번호


    open-in-view: false

    properties:
      hibernate:
        format_sql: true             # 하이버네이트가 실행한 SQL을 출력할 때 보기 좋게 정렬
        show_sql: true               # 하이버네이트가 실행한 SQL을 출력
        jdbc:
          batch_size: 100              #   insert/update 쿼리를 원하는 개수만큼 모아서 DB에 날릴 수 있는 옵션
        default_batch_fetch_size: 100
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  # Redis setting
  data:
    redis:
      host: localhost
      port: 6379

# jwt setting
jwt:
  secret-key:
    access: TestAccessKey111111122222222223333333333333aaaaaaaaabbbbbbbbccccccccdddddddddfqwrqwfqwifjaisfjoihfoiqwflasjdglkkjasdlgjlkasdgjiowejgliasjglasjdgio
    refresh: TestRefreshKey111111122222222223333333333333aaaaaaaaabbbbbbbbccccccccdddddddddfqwrqwfqwifjaisfjoihfoiqwflasjdglkkjasdlgjlkasdgjiowejgliasjglasjdgio
    signup: TestSignupKey111111122222222223333333333333aaaaaaaaabbbbbbbbccccccccdddddddddfqwrqwfqwifjaisfjoihfoiqwflasjdglkkjasdlgjlkasdgjiowejgliasjglasjdgio

  expired-min:
    access: 60   # 액세스 토큰 만료제한시간 60분 (1시간)
    refresh: 10080  # 리프레쉬 토큰 만료제한시간 10080분 (7일)
    signup: 5

# firebase setting


# log 관리
logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      org.hibernate.SQLQuery: debug


# 공공데이터
public-data:
  key: 734364614c73656e32386579495665


server:
  ssl:
    enabled: false

openvidu:
  url: http://localhost:4443/
  secret: MY_SECRET


# OAUTH2.0 Setting
oauth:
  kakao:
    client-id: 8e8a2a929b0cbf786ac9567191ac7ff7
    client-secret: OaZuL5rd6IcxxcwDd4pgcKRnJP9afsHo
    redirect-uri: http://localhost:8080/api/v1/oauth/kakao/login
    scope:
      - profile_nickname
      - profile_image
      - account_email
      - name

  naver:
    client-id: d5K9OtbM_JbyOZIiOG54
    client-secret: UAm7jJPmsC
    redirect_uri: http://localhost:8080/api/v1/oauth/naver/login
    scope:
      - nickname
      - name
      - email
      - profile_image