spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 8fbf9a5fef015750849e18b8ff654d3c
            client-secret: CXN85NWOwzDtmP76Z7ckhJmIPrSgwnA6
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id